In [5]:
import numpy as np

In [16]:
positivos = np.linspace(start = 0, stop = 10, num = 11, dtype = 'float')
print(positivos)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [20]:
multiplos = np.arange( start=2, stop=21, step=2)
print(multiplos)

[ 2  4  6  8 10 12 14 16 18 20]


In [23]:
reverso = np.arange(start=10, stop=0, step=-1)
print(reverso)

[10  9  8  7  6  5  4  3  2  1]
